### ISSUE TITLE
这bug有点吓人

### ISSUE THREAD

**Issue by yyman001** [galnetwen/Live2D#3]
估计是没处理好窗口缩放或资源加载图片的问题渲染
![snipaste_2018-06-11_10-15-15](https://user-images.githubusercontent.com/5688485/41209806-67c89c9e-6d60-11e8-93a3-00f1e92c7c8c.png)

触发,开发工具-拉伸下窗口大小

**Comment by Zephylaci** [comment]
我也遇到过这种的....要怎么做错误处理呢...
偶尔还有加载不出来，console.log一直有输出的情况..
js是压缩的，调整起来实在难

**Comment by shadowjohn** [comment]
打開 live2d.min.js 找
default.DEBUG_MOUSE_LOG && console.log("onMouseMove device( x:" + t.clientX + " y:" + t.clientY + 


有三個地方 #729、#750、#764 
(注，750行左右的是 onMouseDown)

			n = m(o.x - i.left),
			s = T(o.y - i.top);
      if(isNaN(n)) n = 1;    //By Feather Mountain
      if(isNaN(s)) s = 1;    //By Feather Mountain      
		w.
	default.DEBUG_MOUSE_LOG && console.log("onMouseMove device( x:" + t.clientX + " y:" + t.clientY + " ) view( x:" + n + " y:" + s + ")"), Y && (k = e, V = r, N.setPoint(n, s))
	}

即可改善

debug 的過程是打開 506、507行
DEBUG_LOG: 1,
DEBUG_MOUSE_LOG: 1,

就會看到有時  n 會變成 NaN，變成空洞臉

詳見：https://3wa.tw/blog/blog.php?id=1940
