### ISSUE TITLE
live2d.js:formatted:305 Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by Zephylaci** [galnetwen/Live2D#4]
点击事件报错..如题..虽然不影响什么..但是..看着报错总觉得很不爽....压缩JS可谓是调都没法调..

**Comment by Zephylaci** [comment]
跟了一下..看起来似乎是报错出在..判断点击，判断点在哪了..(比如脸，或者身子之类)...可是参数传递的途中有一个变成undefined了..问题是为啥会出这个问题..

**Comment by Ahrwing** [comment]
try catch包一下试试

**Comment by Zephylaci** [comment]
@Ahrwing 最后解决了，原因是这个库添加了点击判断，而早期的模型文件里没有相关的参数，找了个不报错的博客，把配置文件拖下来对比添加上就好了
