### ISSUE TITLE
大小问题，

### ISSUE THREAD

**Issue by CalmCenter** [galnetwen/Live2D#7]
怎么设置大小呢？
![image](https://user-images.githubusercontent.com/19755937/57423645-68eb3400-7247-11e9-8c4c-0ab11ead9ce9.png)
很多设置高的地方都试过了，没有用。。。。。 帽子被截断了~

**Comment by galnetwen** [comment]
id="landlord"
canvas id="live2d" width="280" height="250"

调整这两个元素的大小即可。

**Comment by CalmCenter** [comment]
嗯嗯，试过了 不行呀~  是我加的太小了吗？  我最后  缩放了= = 改了 model.json 里的 "width":1.8  竟然是缩放 。。。。。

**Comment by galnetwen** [comment]
能用就行呢，我好久没整，也忘了……
